### PR TITLE
added_new_bmi_output_variable

### PR DESCRIPTION
**Pull request by ajkhattak**
The PR adds `SOIL_TO_GW_FLUX` (percolation) variable to BMI output list for our baseline simulations. The code was already computing this variable to so no changes to the functionality.

## Additions
- Added a new variable to the BMI output list

## Removals
- None

## Testing
1. The changes have been tested against the master branch, and the branch yields identical results

## Checklist
- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Passes all existing automated tests
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

**Comment by SnowHydrology** [comment]
@ajkhattak Do we need to add any other output vars to CFE or is this it for NWM Baseline?

**Comment by ajkhattak** [comment]
This is the only missing output variable in CFE for the NWM baseline

**Review by SnowHydrology — CHANGES_REQUESTED** [review]
@ajkhattak, the changes look good, but the unit test build fails (see #89). Can you update that so we can unit test the updated BMI functionality? Thanks

**Comment by ajkhattak** [comment]
@SnowHydrology sure, we haven't updated the `unittest` in a while, so let me see what's going on there.

**Review by SnowHydrology — APPROVED** [review]

**Pull request merged**
