### PR TITLE
Splitting forcing_code/ into extern/forcing_code/ and extern/pet/

### PR DESCRIPTION
**Pull request by WanruWu-NOAA**
This PR is for replacing the subdirectory `forcing_code/` with adding `extern/forcing_code/` from the [aorc_bmi repo](https://github.com/NOAA-OWP/aorc_bmi.git) and adding `extern/pet/` from the [evapotranspiration repo](https://github.com/NOAA-OWP/evapotranspiration.git) directly so that all the code under the original `forcing_code/` can be updated automatically in this new structure.

## List to be committed:
	new file:   .gitmodules
	new directory:   extern/forcing_code/
	new directory:   extern/pet/
	deleted:    forcing_code/include/PEtAerodynamicMethod.h
	deleted:    forcing_code/include/PEtCombinationMethod.h
	deleted:    forcing_code/include/PEtEnergyBalanceMethod.h
	deleted:    forcing_code/include/PEtPenmanMonteithMethod.h
	deleted:    forcing_code/include/PEtPriestleyTaylorMethod.h
	deleted:    forcing_code/include/aorc.h
	deleted:    forcing_code/include/aorc_tools.h
	deleted:    forcing_code/include/bmi_aorc.h
	deleted:    forcing_code/include/bmi_pet.h
	deleted:    forcing_code/include/pet.h
	deleted:    forcing_code/include/pet_tools.h
	deleted:    forcing_code/src/aorc.c
	deleted:    forcing_code/src/bmi_aorc.c
	deleted:    forcing_code/src/bmi_pet.c
	deleted:    forcing_code/src/pet.c
	modified:   CMakeLists.txt
	modified:   README.md
	modified:   src/main_cfe_aorc_pet.c
	modified:   src/main_cfe_aorc_pet_rz_aet.cxx
	modified:   src/main_pass_forcings.c

## Additions
Adding two submodules extern/forcing_code and extern/pet: 

-   .gitmodules (adding path and url for submodule "extern/forcing_code" and submodule "extern/pet")
-   extern/forcing_code (adding from https://github.com/NOAA-OWP/aorc_bmi.git) 
-   extern/pet (adding from https://github.com/NOAA-OWP/evapotranspiration.git)

## Removals
Deleting forcing_code/:

-  forcing_code/include/PEtAerodynamicMethod.h
-  forcing_code/include/PEtCombinationMethod.h
-  forcing_code/include/PEtEnergyBalanceMethod.h
-  forcing_code/include/PEtPenmanMonteithMethod.h
-  forcing_code/include/PEtPriestleyTaylorMethod.h
-  forcing_code/include/aorc.h
-  forcing_code/include/aorc_tools.h
-  forcing_code/include/bmi_aorc.h
-  forcing_code/include/bmi_pet.h
-  forcing_code/include/pet.h
-  forcing_code/include/pet_tools.h
-  forcing_code/src/aorc.c
-  forcing_code/src/bmi_aorc.c
-  forcing_code/src/bmi_pet.c
-  forcing_code/src/pet.c

## Changes
Modifying corresponding paths:

- CMakeLists.txt
- README.md
- src/main_cfe_aorc_pet.c
- src/main_cfe_aorc_pet_rz_aet.cxx
- src/main_pass_forcings.c

## Testing

- tested in the ngen framework
- tested on Linux

## Notes

- There have been some changes for cfe repository since [the previous PR submitted for adding extern/forcing_code](https://github.com/NOAA-OWP/cfe/pull/70), which can be deleted/closed without further processing. 
- This new PR has combined both adding extern/forcing_code/ and adding extern/pet/, as well as deleting the original  forcing_code/.

## Todos

- Can do further test if needed.

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [ ] Passes all existing automated tests
- [ ] Any _change_ in functionality is tested
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged / future todos are captured in comments
- [ ] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [ ] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Target Environment support

- [ ] Windows
- [x] Linux
- [ ] Browser

### Accessibility

- [ ] Keyboard friendly
- [ ] Screen reader friendly

### Other

- [ ] Is useable without CSS
- [ ] Is useable without JS
- [ ] Flexible from small to large screens
- [ ] No linting errors or warnings
- [ ] JavaScript tests are passing

### CODE REVIEW

**Comment by SnowHydrology** [comment]
@WanruWu-NOAA does a clean build of this code run for you as-is? I'm getting a seg fault when trying to run:
```
./run_cfe.sh FORCINGPET
CFE running with option FORCINGPET
config file: ./configs/cat_87_bmi_config_cfe_pass.txt ./configs/cat_87_bmi_config_aorc.txt ./configs/cat_87_bmi_config_pet_pass.txt
allocating memory to store entire BMI structure for CFE
allocating memory to store entire BMI structure for AORC
allocating memory to store entire BMI structure for PET
Registering BMI CFE model
Registering BMI AORC model
Registering BMI PET model
Initializeing BMI CFE model
Initializeing BMI AORC model
AORC config file ./configs/cat_87_bmi_config_aorc.txt
./run_cfe.sh: line 38: 90499 Segmentation fault: 11  ./build/${exe_name} $args
```

**Comment by WanruWu-NOAA** [comment]
@SnowHydrology Hmm, I couldn't run it, see the screenshot below
image

**Comment by SnowHydrology** [comment]
@WanruWu-NOAA, it doesn't look like the executable has been built. Did you follow the instructions to build FORCINGPET in the README?

**Comment by WanruWu-NOAA** [comment]
@SnowHydrology thanks for the reminder :-) I followed this:
```
  git clone https://github.com/NOAA-OWP/cfe.git
  cd cfe
  git checkout ajk/sft_aet_giuh_merge
  mkdir build && cd build
  cmake ../ -DFORCINGPET=ON
  make
  sed -i -e 's/\r$//' run_cfe.sh
  ./run_cfe.sh FORCINGPET
```
and got this:
```
[wanru.wu@nwcal-apd-dev1 cfe]$ ./run_cfe.sh FORCINGPET
CFE running with option FORCINGPET
config file: ./configs/cat_87_bmi_config_cfe_pass.txt ./configs/cat_87_bmi_config_aorc.txt ./configs/cat_87_bmi_config_pet_pass.txt
allocating memory to store entire BMI structure for CFE
allocating memory to store entire BMI structure for AORC
allocating memory to store entire BMI structure for PET
Registering BMI CFE model
Registering BMI AORC model
Registering BMI PET model
Initializeing BMI CFE model
' could not be opened for reading
Initializeing BMI AORC model
AORC config file ./configs/cat_87_bmi_config_aorc.txt
File does not exist.
 Failed in function read_file_line_counts
' could not be opened for readinggs/cat87_01Dec2015.csv
Initializeing BMI PET model
File does not exist.
 Failed in function read_file_line_counts_pet
' could not be opened for reading
Get the information from the configuration here in Main
forcing file for the CFE module BMI
forcing file for the PET module BMI
forcing file for the AORC module ./forcings/cat87_01Dec2015.csv
The model time step size is: 3600.000000
looping through and calling update
#    ,            hourly ,  direct,   giuh ,lateral,  base,   total, storage, ice fraction, ice fraction
Time [h],rainfall [mm],runoff [mm],runoff [mm],flow [mm],flow [mm],discharge [mm],storage [mm],schaake [mm],xinan [-]
./run_cfe.sh: line 38: 35458 Segmentation fault      (core dumped) ./build/${exe_name} $args
```

**Comment by SnowHydrology** [comment]
@WanruWu-NOAA, it looks like there's a bit of work left before I can review the PR

**Comment by WanruWu-NOAA** [comment]
@SnowHydrology Yeah, the compiling and running cfe which I did yesterday was for the current cfe version before any changes from this PR.

**Comment by WanruWu-NOAA** [comment]
@SnowHydrology I'm going to close this PR to avoid any confusion as it was basically same as the combination of PR#78 and PR#79.

**Pull request closed without merging**
