### PR TITLE
Tighten CI checks

### PR DESCRIPTION
**Pull request by PhilMiller**
We want to ensure code quality issues get caught relatively early, before they cause problems in ngen integration tests on updates.

## Changes

- Enable AddressSanitizer (ASan)
- Build with `-Werror` (including `-Og` to get control/data-flow analysis for necessary warnings)
- Stop smashing CMake options that the user may have set on the command line

## Testing

1. CI

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Visually tested in supported browsers and devices (see checklist below :point_down:)
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### Target Environment support

- [x] Linux
- [x] macOS

### CODE REVIEW

**Comment by PhilMiller** [comment]
(to be rebased and merged after #106)

**Review by aaraney — APPROVED** [review]
Thanks for improving CI! I doubt you removing the ability to specify the C and Cpp compilers Cmake uses via environment variables will affect anyone. But, just to be on the safe side will you please update the PR description to reflect that this is a potential breaking change to the build process and show how to fix this (e.g. `-DCMAKE_C_COMPILER='gcc'`)?

**Comment by PhilMiller** [comment]
It doesn't actually remove any ability. CMake already checks those environment variables, without anything in `CMakeLists.txt`

**Comment by PhilMiller** [comment]
E.g. https://cmake.org/cmake/help/latest/envvar/CC.html

**Comment by aaraney** [comment]
The more you know. I knew it was at least conventional, didn't realize it was a feature. Thanks for the link!

**Pull request merged**
