### PR TITLE
pre-CFE2.0_PR

### PR DESCRIPTION
**Pull request by ajkhattak**
This PR is based on PR #116 and the current master. It wraps up the full capability of Nash Cascade-based surface runoff with `backward compatibility`. An example config and realization files are provided to turn ON `Nash_Cascade surface runoff` scheme. The old scheme `GIUH-based surface runoff` has been retained, and is the default option. 

Based on the discussion with Fred, the commit `6d08db7bec2ec6cc2cc2446300c9e0d2076e0fc7` should be tagged as CFE1.0, and the new version will be CFE2.0 (previously we were mistakenly calling it CFE3.0)

**NOTE: CFE2.0 defaults to CFE1.0.**

## Additions
- Added runon infiltration, retention depth, and calibratable parameters in addition to changes in PR #116 

## Removals
- None

## Changes
- see PR #116 

## Testing
1. All existing tests have been tested, and old and new results are identical. 
2. All configuration files have been tested to work on both CFE1.0 and CFE2.0

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [ ] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

**Comment by madMatchstick** [comment]
@ajkhattak - I was able to run the new `realization_cfe_pet_surfnash_calib.json` after typeo fix - thanks!  Although I did not look into results just yet.   

Noting that the ngen integration tests use the existing giuh default option; `realization_cfe_pet_surfgiuh.json` - just a file name change for clarity.

**Comment by ajkhattak** [comment]
@madMatchstick `realization_cfe_pet_surfnash_calib.json` will be added to CI, along with a few other minor changes, once this PR is done. 
To compare the results of cfe1.0 vs this PR, I would use our four tests, if those results look okay, we are good.

**Comment by madMatchstick** [comment]
@ajkhattak -  Very minor recommended changes:

1. [Install.md](https://github.com/NOAA-OWP/cfe/blob/master/INSTALL.md#cfe) - go ahead and include the correct cfe lib path based on realizations, CI, etc. So,
```
cmake -B extern/cfe/cfe/cmake_build -S extern/cfe/cfe/ -DNGEN=ON
make -C extern/cfe/cfe/cmake_build
```
2. Question - why are we building [fortran bmi ](https://github.com/NOAA-OWP/cfe/blob/master/INSTALL.md#fortran-bmi) for this example?  We aren't coupling with NOM?  Also not seeing instructions for PET lib build?  Little confused here...
3. Probably best to change ` "model_type_name": "bmi_multi_noahowp_cfe"` to something like `"bmi_multi_cfe_pet"` for good measure. [Here](https://github.com/NOAA-OWP/cfe/blob/8872e17354d296033a46d78b50564e466a03b740/realizations/realization_cfe_pet_surfgiuh.json#L7C20-L7C64) & [here](https://github.com/NOAA-OWP/cfe/blob/8872e17354d296033a46d78b50564e466a03b740/realizations/realization_cfe_pet_surfnash_calib.json#L7C20-L7C64). 

-Thanks!

**Review by madMatchstick — APPROVED** [review]
@ajkhattak - Thanks for the recent commits.  I do not see any major problems with this PR.  We should probably start using [releases](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases) for code versioning?

**Pull request merged**
